{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.12/toolkit-core-0.2.12.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-js-0.2.12.klib",
          "url": "toolkit-core-js-0.2.12.klib",
          "size": 94856,
          "sha512": "6a6ece4272bd58454132d451c3e83799c2acb0d036af6fd2ce03c6f251ef2988d601a49004767dfd12f9eeaacd87769b457996181f83c8047c5df02bf26da050",
          "sha256": "b7d44e5982e208916295c9eaacfa4d72871f81937b44c7838f516f160a2ec219",
          "sha1": "12acbcd54371d384b93e629b59cd3b9d9ce4db7e",
          "md5": "ee85ca7ee792ecf87a54651fa4422319"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-js-0.2.12.klib",
          "url": "toolkit-core-js-0.2.12.klib",
          "size": 94856,
          "sha512": "6a6ece4272bd58454132d451c3e83799c2acb0d036af6fd2ce03c6f251ef2988d601a49004767dfd12f9eeaacd87769b457996181f83c8047c5df02bf26da050",
          "sha256": "b7d44e5982e208916295c9eaacfa4d72871f81937b44c7838f516f160a2ec219",
          "sha1": "12acbcd54371d384b93e629b59cd3b9d9ce4db7e",
          "md5": "ee85ca7ee792ecf87a54651fa4422319"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-core-js-0.2.12-sources.jar",
          "url": "toolkit-core-js-0.2.12-sources.jar",
          "size": 30623,
          "sha512": "5bbd8f0c95cc4b8a2b3cd50b34825b2164f5f2f7b7ce05b67d4a99cfca624538d8cd8ff9f779df4b529dbc5053aa20a9376ee8ae6db5189470ed192c0ba27b9e",
          "sha256": "4ba8e67f39ebe5fefe4534fab7ed6b0462b276f1bc44d4a8f4e831aedc4cebd4",
          "sha1": "26c09f0b3d090e2d0c8663a5f398c933f12c47dc",
          "md5": "70403f6326e7d998c64df00befc47d8f"
        }
      ]
    }
  ]
}
