{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.1.4/toolkit-store-0.1.4.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-js-0.1.4.klib",
          "url": "toolkit-store-js-0.1.4.klib",
          "size": 41095,
          "sha512": "6f536e19f1f9f9c5bffd8f93a504a1fdd20928fcefb2e9a49d19bb978ef87218a11524eafb4989afd2e9ed646b7f23b4b76a48eceffc7e4b2799970555231b8d",
          "sha256": "1e185596d20d4a1c9c8926a387ea08f346a48b7c9fedfde3e53fb3a249cb7349",
          "sha1": "ec2d3fc96ecf53f026f108b8b09a0cd9d5dab703",
          "md5": "7c7fed69fa63c87785c7da44f5788769"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-js-0.1.4.klib",
          "url": "toolkit-store-js-0.1.4.klib",
          "size": 41095,
          "sha512": "6f536e19f1f9f9c5bffd8f93a504a1fdd20928fcefb2e9a49d19bb978ef87218a11524eafb4989afd2e9ed646b7f23b4b76a48eceffc7e4b2799970555231b8d",
          "sha256": "1e185596d20d4a1c9c8926a387ea08f346a48b7c9fedfde3e53fb3a249cb7349",
          "sha1": "ec2d3fc96ecf53f026f108b8b09a0cd9d5dab703",
          "md5": "7c7fed69fa63c87785c7da44f5788769"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-store-js-0.1.4-sources.jar",
          "url": "toolkit-store-js-0.1.4-sources.jar",
          "size": 14040,
          "sha512": "52f0e081b218986c4ed2b8976e7e07ed4a1810f5267d612cab2a3f938de910a659734be0b1987ce1f2f5eb813ff2490590616a3fd69d4be5ca6a592a15af5ed5",
          "sha256": "a85e5f56771d66cb675a6f6ae00e78c4bed3ba456b991799799170918d991e1b",
          "sha1": "372f353f52cba6883cfd982ff8f2eb96063072f6",
          "md5": "85a8a14ec67ff3784f55c9a8a0024d9e"
        }
      ]
    }
  ]
}
