{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.1/toolkit-web-0.2.1.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.1.klib",
          "url": "toolkit-web-js-0.2.1.klib",
          "size": 630842,
          "sha512": "de3fde6fe7d59c0a81a7f818359793b20273ecdfccb78b396a6beadfd78117f921df2d486f3ee973085cd996a471a73ce7c2df139183e915d735a2065d385682",
          "sha256": "ac7d213c823383eb7c00111b2943a2e6e1ec0491fb16a40022ac938310c6eb43",
          "sha1": "d9dabe6baac5cd95fb0696e48942d9ff7418df63",
          "md5": "8daaed34e3a44b863497b4b848042ed4"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.1.klib",
          "url": "toolkit-web-js-0.2.1.klib",
          "size": 630842,
          "sha512": "de3fde6fe7d59c0a81a7f818359793b20273ecdfccb78b396a6beadfd78117f921df2d486f3ee973085cd996a471a73ce7c2df139183e915d735a2065d385682",
          "sha256": "ac7d213c823383eb7c00111b2943a2e6e1ec0491fb16a40022ac938310c6eb43",
          "sha1": "d9dabe6baac5cd95fb0696e48942d9ff7418df63",
          "md5": "8daaed34e3a44b863497b4b848042ed4"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.1-sources.jar",
          "url": "toolkit-web-js-0.2.1-sources.jar",
          "size": 257358,
          "sha512": "82dc99272e3d65ad8603f5ac552dc29cc1461233f5c9232fe7588ee081cc64f3b0c9e10d7a57e54a922d01a8ac801d1a68eee888377357464a70422d10514836",
          "sha256": "4656dc00c46f5040c8a2feabc70bc0c6f9f4a9fc3b7a667fefa41dfd5cd16fa1",
          "sha1": "245a067387aa8b4cda2ab65e12dda68f8b5d8740",
          "md5": "ba38ee9e710d78da9d057e2c1e0af290"
        }
      ]
    }
  ]
}
