{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.2.16/toolkit-store-0.2.16.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosArm64Main-0.2.16.klib",
          "url": "toolkit-store-iosarm64-0.2.16.klib",
          "size": 44673,
          "sha512": "f8b606ef8e536869b1b5349f7f302406b1cc5430033babdcc752fb579c7e1650ea76c48fe3c94d3193615d0ec00b4be0a21a094408deca236e98faa213029209",
          "sha256": "94e31e6c1d5b51528c0e50149c35045a4199bc002ccf86db89dca505580a8092",
          "sha1": "c0468617b2ed16ab27399ed97a6882209d414581",
          "md5": "9db3b5388f1e6eb53a700107bcfdd219"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-store-iosarm64-0.2.16-sources.jar",
          "url": "toolkit-store-iosarm64-0.2.16-sources.jar",
          "size": 13564,
          "sha512": "1e8d4691ecbbcf05087ef4e07a393a02c990fc1461c8f57f7bf7ca8c7c78d080505b35de1b3391cd948c7b9f5dd868eb78154fdfc371850ef784e967fd53efb6",
          "sha256": "8ee9c2fd5d255a51d8274892032028292ee844f5f5425729af2784f75991f724",
          "sha1": "b116f57e4a99c0ebf46eb20472c563bd743251ca",
          "md5": "b9fc5333cf3de2c670375e9256660200"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosarm64-0.2.16-metadata.jar",
          "url": "toolkit-store-iosarm64-0.2.16-metadata.jar",
          "size": 3865,
          "sha512": "45c4f3ec8c1473a9d17dbe6bbdec7fb2706e81fafda6769bce1c78af7b7b88051c27fdcb827e12463a9238367a819540f23b7ae86d2a9cd095b3c07ffe8d7d61",
          "sha256": "26e8782f902bae3e72d8bbadefcde61b98cb8db8a4e334fcbe9c1cd4dbbda6d7",
          "sha1": "20a2dab96c40b9b7c321fcc696f775764ce9b48e",
          "md5": "23280363c9122b9417ffdb00f8380e9a"
        }
      ]
    }
  ]
}
