{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.1.1/toolkit-core-0.1.1.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.1.1.jar",
          "url": "toolkit-core-jvm-0.1.1.jar",
          "size": 133319,
          "sha512": "78ff912a9e5a848fa4b7d2d720918844439bb8676e3e573746bf55af8e0c3aeab1e937a8bbd330425df129477000281cc2f855d8350f1b48ef224b71d5df5ab3",
          "sha256": "a6f2bd251f3b5280bf3fbc15271b03460a05448e5ca054a570c8c94d29d55c20",
          "sha1": "efcc0fb557d4956a5ccfc09cb6a21612ff899ae0",
          "md5": "f2ca0312a425f515f4668691d0f90907"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.1.1.jar",
          "url": "toolkit-core-jvm-0.1.1.jar",
          "size": 133319,
          "sha512": "78ff912a9e5a848fa4b7d2d720918844439bb8676e3e573746bf55af8e0c3aeab1e937a8bbd330425df129477000281cc2f855d8350f1b48ef224b71d5df5ab3",
          "sha256": "a6f2bd251f3b5280bf3fbc15271b03460a05448e5ca054a570c8c94d29d55c20",
          "sha1": "efcc0fb557d4956a5ccfc09cb6a21612ff899ae0",
          "md5": "f2ca0312a425f515f4668691d0f90907"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-core-jvm-0.1.1-sources.jar",
          "url": "toolkit-core-jvm-0.1.1-sources.jar",
          "size": 56147,
          "sha512": "1d0c38afdb8c994040cb68884e4686103e2fbcb860378f63ba907465df80d7bfceda2c0beb7d74edefa07b4a5055d010fc80f92e586d9f72a5c966c564a893ee",
          "sha256": "17c71597dad5f3ac723bb13ce7de2783b88b4625f1a5820ffa534a064a2606cb",
          "sha1": "c518ad71295c7ee773b9c3606c112bf77d6e6d28",
          "md5": "e25209611a9850f744164a2d1c260c5a"
        }
      ]
    }
  ]
}
