{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.1.3/toolkit-store-0.1.3.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosSimulatorArm64Main-0.1.3.klib",
          "url": "toolkit-store-iossimulatorarm64-0.1.3.klib",
          "size": 45301,
          "sha512": "98d290a1eb49c511db85598e9458db8be37ab030f16756063b6e8526b26585e74baff4a387314b61e3d9d67e76579ce975bb79e00ee0c98bb2e8c252d271ba6a",
          "sha256": "558f2f16e39e59e5a83b4fc33d8bb498f379f5cabc68816603cbf467cd55f623",
          "sha1": "9b5d304bcd3e369163dc07c7bde8b6586b013eae",
          "md5": "9c0bba5ef45b90d5c70c27e36d7d0622"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-store-iossimulatorarm64-0.1.3-sources.jar",
          "url": "toolkit-store-iossimulatorarm64-0.1.3-sources.jar",
          "size": 14027,
          "sha512": "ed851b1bd2b5135acea4b72a97cc09160a9c046faadb1f9872223f7599f93f4fdb091abcb81921b76f989ac2c4704f4aaef5106c362171801d99804effec60b9",
          "sha256": "a16bdff163bcba2ac763104f8ca2ff6f71332c2b6bc12eec25e5a1acbd2c9234",
          "sha1": "3f64e6fa755444b5a84fa719bdd7440cfff47db8",
          "md5": "97ad9736cdf85bce98f7400d2e5cbfd0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iossimulatorarm64-0.1.3-metadata.jar",
          "url": "toolkit-store-iossimulatorarm64-0.1.3-metadata.jar",
          "size": 3972,
          "sha512": "6b2cb76f054a684b94775e0a9944b1f556ada0fa18e581b0be6bb3268fde1c6ef0d963ecd0a58961f06253314a5150079b0f989335fe802e7529954c7075dcf4",
          "sha256": "11501c4ace133f780bda80b9d56a780f73a63d30487bc0e74ebf9eaef05128ca",
          "sha1": "38151eb74f23e0a2c09e31eb768e531799850d17",
          "md5": "1525c07751fddb0dbddd8e2a898ee252"
        }
      ]
    }
  ]
}
