{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.1.1/toolkit-store-0.1.1.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-jvm-0.1.1.jar",
          "url": "toolkit-store-jvm-0.1.1.jar",
          "size": 44586,
          "sha512": "5fd0f00f42538d3a3e6dda88d7c692a998c933d151d480d1aa998eb42363e9120db0ef52094c8c35e974add9ec21c50dfd24c57d6775e67b225699526087b695",
          "sha256": "4eca1adda74edf1545a568619795ada77b2bbf060ae72636c99e1252ce020a8f",
          "sha1": "78851c3f89d4bfc6ba08def09b69f315e08cec3f",
          "md5": "a24159b241e84fc796b11b962962b268"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-jvm-0.1.1.jar",
          "url": "toolkit-store-jvm-0.1.1.jar",
          "size": 44586,
          "sha512": "5fd0f00f42538d3a3e6dda88d7c692a998c933d151d480d1aa998eb42363e9120db0ef52094c8c35e974add9ec21c50dfd24c57d6775e67b225699526087b695",
          "sha256": "4eca1adda74edf1545a568619795ada77b2bbf060ae72636c99e1252ce020a8f",
          "sha1": "78851c3f89d4bfc6ba08def09b69f315e08cec3f",
          "md5": "a24159b241e84fc796b11b962962b268"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-store-jvm-0.1.1-sources.jar",
          "url": "toolkit-store-jvm-0.1.1-sources.jar",
          "size": 18539,
          "sha512": "7c3f270b3e31a22e6dc4233d07ab3077b09bd95262da102e811f78ef1ba7f0fe2b7fc8b2ba66e2242a9ef6a9d9f7bc45c4fea1f813e441901b5d95142272acc0",
          "sha256": "c94d1fc34db0fef5df3c290719cc89c2db1586eeaecfddd032c9f5144042a52e",
          "sha1": "ba0714dddeffcc12e3e95bfe156597df530a84d3",
          "md5": "5bd3490d4f5de597d12c5b51dbad5a59"
        }
      ]
    }
  ]
}
