{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.1.3/toolkit-store-0.1.3.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosArm64Main-0.1.3.klib",
          "url": "toolkit-store-iosarm64-0.1.3.klib",
          "size": 45235,
          "sha512": "476de0bd5b3dc7c7185018ba42804ffdbb6f8fb9f9e9dcdcec6e423686b781c264e4458c564f805dfa2e846a5bffd25218d1b3fa57725c7fcea74a21f35304ef",
          "sha256": "04723472c1b67a3d03c29fcfa6ee12b9991081de07f56d86f1e90c92a0bf60ef",
          "sha1": "8450fac5e9e43aab42e071f782549d75785c3f57",
          "md5": "9359b4cdc57b3ebec9efad6f872002d2"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-store-iosarm64-0.1.3-sources.jar",
          "url": "toolkit-store-iosarm64-0.1.3-sources.jar",
          "size": 14027,
          "sha512": "ed851b1bd2b5135acea4b72a97cc09160a9c046faadb1f9872223f7599f93f4fdb091abcb81921b76f989ac2c4704f4aaef5106c362171801d99804effec60b9",
          "sha256": "a16bdff163bcba2ac763104f8ca2ff6f71332c2b6bc12eec25e5a1acbd2c9234",
          "sha1": "3f64e6fa755444b5a84fa719bdd7440cfff47db8",
          "md5": "97ad9736cdf85bce98f7400d2e5cbfd0"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosarm64-0.1.3-metadata.jar",
          "url": "toolkit-store-iosarm64-0.1.3-metadata.jar",
          "size": 3972,
          "sha512": "6b2cb76f054a684b94775e0a9944b1f556ada0fa18e581b0be6bb3268fde1c6ef0d963ecd0a58961f06253314a5150079b0f989335fe802e7529954c7075dcf4",
          "sha256": "11501c4ace133f780bda80b9d56a780f73a63d30487bc0e74ebf9eaef05128ca",
          "sha1": "38151eb74f23e0a2c09e31eb768e531799850d17",
          "md5": "1525c07751fddb0dbddd8e2a898ee252"
        }
      ]
    }
  ]
}
