{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.0/toolkit-core-0.2.0.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.0.jar",
          "url": "toolkit-core-jvm-0.2.0.jar",
          "size": 77830,
          "sha512": "885fb3a71759d18399faaeea1dc4153d61fcae8024c0ff08557ec80b9d37f52de7c4c912f454e8c0e40e55357f34aa48564588dd2807afeaff299a7082abcc94",
          "sha256": "acdf70ae2bd6d4510eec535bec571c0280a7ad22300ad8244c3940d35f33aa9b",
          "sha1": "e518b2dd99bf8fa9927d951952c279a308deb707",
          "md5": "dd847bfc06e73010e3c4e9f80954575c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.0.jar",
          "url": "toolkit-core-jvm-0.2.0.jar",
          "size": 77830,
          "sha512": "885fb3a71759d18399faaeea1dc4153d61fcae8024c0ff08557ec80b9d37f52de7c4c912f454e8c0e40e55357f34aa48564588dd2807afeaff299a7082abcc94",
          "sha256": "acdf70ae2bd6d4510eec535bec571c0280a7ad22300ad8244c3940d35f33aa9b",
          "sha1": "e518b2dd99bf8fa9927d951952c279a308deb707",
          "md5": "dd847bfc06e73010e3c4e9f80954575c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.0-sources.jar",
          "url": "toolkit-core-jvm-0.2.0-sources.jar",
          "size": 30354,
          "sha512": "e0ac19659bc0ce0fdbee13ef1ca1a760cd564e543681d7dc61eac1d4c4df4b87d00add402f5ff12e7766b1ed40eababd9090d985593f10b5b6921d49268ed251",
          "sha256": "925b11edd673510395469156bd0548e6c0f4234237727d4d48935e758c6ce73c",
          "sha1": "1c10482b7c393cbf36af436629229429346b06ea",
          "md5": "5025f4d132c82eee54ee752e9c367378"
        }
      ]
    }
  ]
}
