{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-compose/0.1.1/toolkit-compose-0.1.1.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-compose",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-compose-jvm-0.1.1.jar",
          "url": "toolkit-compose-jvm-0.1.1.jar",
          "size": 4993,
          "sha512": "00ddbf963a366800ba3b3b2beb5102bbeff1f46fdb1c3a379e7a43858ba7f03449b849e38a23a1d7b031d92b03c383e54c0e0c1972823a7d7cc1f9db57a95349",
          "sha256": "59f76b3de349eca1d35ff89c92197485ced28ded1e467e4feca8215b4816b552",
          "sha1": "9589d30358719a53065775757479807fd5b2fb56",
          "md5": "91a15e67649139a75b3405dc8647c5b0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-compose-jvm-0.1.1.jar",
          "url": "toolkit-compose-jvm-0.1.1.jar",
          "size": 4993,
          "sha512": "00ddbf963a366800ba3b3b2beb5102bbeff1f46fdb1c3a379e7a43858ba7f03449b849e38a23a1d7b031d92b03c383e54c0e0c1972823a7d7cc1f9db57a95349",
          "sha256": "59f76b3de349eca1d35ff89c92197485ced28ded1e467e4feca8215b4816b552",
          "sha1": "9589d30358719a53065775757479807fd5b2fb56",
          "md5": "91a15e67649139a75b3405dc8647c5b0"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-compose-jvm-0.1.1-sources.jar",
          "url": "toolkit-compose-jvm-0.1.1-sources.jar",
          "size": 2313,
          "sha512": "06e772c0d983c76d6de3e66032b99229a9b390d9382844dc452fdea0a89316a747071ebf8db61dce33405611c68585dff10b21ccd86da58ba0d2028ba290be89",
          "sha256": "e089282ea93552720c29ce6e82106afe38ad2d222db7a9489badbd3f27148025",
          "sha1": "da44815e59859b96e0a8c2e84239b33edff9637f",
          "md5": "64d1c8bde9c407fea3d9438ef71e4242"
        }
      ]
    }
  ]
}
