{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.1.3/toolkit-web-0.1.3.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.1.3.klib",
          "url": "toolkit-web-js-0.1.3.klib",
          "size": 719809,
          "sha512": "46280c6f4be681c069fa965e71534dc2abc82590760a623d7cba85eb6e5b235df4fb20e423741dac6a1a58645667248231bfe37510ab9e7bb9390c03109d8d52",
          "sha256": "da4f0e095879f1e4d971e40ea6c0e3bfd9bf9e300ca05c8aa051bec04912b64f",
          "sha1": "210dbe11d621c2d732a2e9e91340b2cb851e87fe",
          "md5": "9dd450f3454bff09b72004255738be22"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.1.3.klib",
          "url": "toolkit-web-js-0.1.3.klib",
          "size": 719809,
          "sha512": "46280c6f4be681c069fa965e71534dc2abc82590760a623d7cba85eb6e5b235df4fb20e423741dac6a1a58645667248231bfe37510ab9e7bb9390c03109d8d52",
          "sha256": "da4f0e095879f1e4d971e40ea6c0e3bfd9bf9e300ca05c8aa051bec04912b64f",
          "sha1": "210dbe11d621c2d732a2e9e91340b2cb851e87fe",
          "md5": "9dd450f3454bff09b72004255738be22"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.1.3-sources.jar",
          "url": "toolkit-web-js-0.1.3-sources.jar",
          "size": 285080,
          "sha512": "6ad8ad14c8f4fa91ebd4a70d1c93f8f8512d2ebb545deff065d8eb2496ad30d8418bb9e55c2586b995b3f651a6a8050d4224bb0f739afa155dc3f7bf5b000126",
          "sha256": "4c9bdd2321a145aa84ce3e1a866542852e89208f5523a05f73c4ef861b0f5101",
          "sha1": "92d188e137614958677dd79b4d25273574210857",
          "md5": "1e2fe7575d0fc36d368311ecfb633b57"
        }
      ]
    }
  ]
}
