{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.1.1/toolkit-core-0.1.1.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iosSimulatorArm64Main-0.1.1.klib",
          "url": "toolkit-core-iossimulatorarm64-0.1.1.klib",
          "size": 190978,
          "sha512": "9c71a2cc58aadf8cc9c1d8c95a8ddc0b237728b3f200c05905209b3d3c17ac1ef5604595d6699dbb07d4201d499251c6401bf79ea5f4c2643c1ccfd59b7c19b4",
          "sha256": "4df72195bb58643d1c764ea0c5bba19245134b2fdd4ad10f785b7e46c72980e5",
          "sha1": "d29c43f65b1f048bb5e960f628cf83b3e759fa8b",
          "md5": "61ffae6415342f2b749509ba7b959658"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-core-iossimulatorarm64-0.1.1-sources.jar",
          "url": "toolkit-core-iossimulatorarm64-0.1.1-sources.jar",
          "size": 56147,
          "sha512": "1d0c38afdb8c994040cb68884e4686103e2fbcb860378f63ba907465df80d7bfceda2c0beb7d74edefa07b4a5055d010fc80f92e586d9f72a5c966c564a893ee",
          "sha256": "17c71597dad5f3ac723bb13ce7de2783b88b4625f1a5820ffa534a064a2606cb",
          "sha1": "c518ad71295c7ee773b9c3606c112bf77d6e6d28",
          "md5": "e25209611a9850f744164a2d1c260c5a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iossimulatorarm64-0.1.1-metadata.jar",
          "url": "toolkit-core-iossimulatorarm64-0.1.1-metadata.jar",
          "size": 261,
          "sha512": "da9ce770cec4fe61d7262e8c3c86e805d2ccac7d3ae8d44b62f5bed8126e76bd9cdb57a8cef585b308764660748d5c1cb70ecd257469cdecee25f19a60fa0855",
          "sha256": "ffaa1fb250d2c6b9d8c38ff927a019c806652baac5c105ab4baf75cd0faf5c58",
          "sha1": "93bba5d0bf6115532207df297d34fcbe061a7844",
          "md5": "59473ad77f611c3210093c922228d943"
        }
      ]
    }
  ]
}
