{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.1.1/toolkit-web-0.1.1.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.1.1.klib",
          "url": "toolkit-web-js-0.1.1.klib",
          "size": 710874,
          "sha512": "f94c1a4ec20f855895d0fd7a0ba1f75ad2abe5830be31b79eff281fc24fc42f6f4f3ba8e433eed2630ada1bafc0ca996c45ba562afa0468ce37090b6c35f70ac",
          "sha256": "93a012dc8de81e317e85df7edb17ff963ae23beb5ce83c5a81419c57fc87f126",
          "sha1": "470ef43f2922dbbbac534da4e32e3d7aebf2cbdf",
          "md5": "3ff51b38eb769210907144cfe31f1402"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.1.1.klib",
          "url": "toolkit-web-js-0.1.1.klib",
          "size": 710874,
          "sha512": "f94c1a4ec20f855895d0fd7a0ba1f75ad2abe5830be31b79eff281fc24fc42f6f4f3ba8e433eed2630ada1bafc0ca996c45ba562afa0468ce37090b6c35f70ac",
          "sha256": "93a012dc8de81e317e85df7edb17ff963ae23beb5ce83c5a81419c57fc87f126",
          "sha1": "470ef43f2922dbbbac534da4e32e3d7aebf2cbdf",
          "md5": "3ff51b38eb769210907144cfe31f1402"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.1.1-sources.jar",
          "url": "toolkit-web-js-0.1.1-sources.jar",
          "size": 280331,
          "sha512": "2ba46584476d351a65ec491dfb794d3cf151e1569acb609075fbc6b3fc9daf801b16a51c04d54aa3eb3819830184f0e623c9c6ba27d60c7f504f583c3f1cf156",
          "sha256": "14d5ca4b060c356cb40d66fa99a677bc1f8fcf2c51fe59bd4a0f777aba3335de",
          "sha1": "62635d4bac944fedefe30e6d68eac25379491182",
          "md5": "cad5e58742cf0b52e88e117869139dbc"
        }
      ]
    }
  ]
}
