{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.1.2/toolkit-store-0.1.2.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosArm64Main-0.1.2.klib",
          "url": "toolkit-store-iosarm64-0.1.2.klib",
          "size": 45235,
          "sha512": "476de0bd5b3dc7c7185018ba42804ffdbb6f8fb9f9e9dcdcec6e423686b781c264e4458c564f805dfa2e846a5bffd25218d1b3fa57725c7fcea74a21f35304ef",
          "sha256": "04723472c1b67a3d03c29fcfa6ee12b9991081de07f56d86f1e90c92a0bf60ef",
          "sha1": "8450fac5e9e43aab42e071f782549d75785c3f57",
          "md5": "9359b4cdc57b3ebec9efad6f872002d2"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-store-iosarm64-0.1.2-sources.jar",
          "url": "toolkit-store-iosarm64-0.1.2-sources.jar",
          "size": 14027,
          "sha512": "ed851b1bd2b5135acea4b72a97cc09160a9c046faadb1f9872223f7599f93f4fdb091abcb81921b76f989ac2c4704f4aaef5106c362171801d99804effec60b9",
          "sha256": "a16bdff163bcba2ac763104f8ca2ff6f71332c2b6bc12eec25e5a1acbd2c9234",
          "sha1": "3f64e6fa755444b5a84fa719bdd7440cfff47db8",
          "md5": "97ad9736cdf85bce98f7400d2e5cbfd0"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosarm64-0.1.2-metadata.jar",
          "url": "toolkit-store-iosarm64-0.1.2-metadata.jar",
          "size": 3972,
          "sha512": "3ae8ede27d209ce6183232619d433692e4774bb168b6c06073e3cb3beb5e3d96dbe55075a666e229611cee699769b3df6e72d74d7192f11314bcd2f2aa1466dc",
          "sha256": "52fd30fda8fef218d505f3ea93932b7f99f5d613624fd84078deefde3f5ad017",
          "sha1": "9f4d78b436dbaf756a40829c38239e09ac93d0d2",
          "md5": "ca0118f3e3c0ec81a2003f01995fe288"
        }
      ]
    }
  ]
}
