{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.1.2/toolkit-web-0.1.2.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.1.2.klib",
          "url": "toolkit-web-js-0.1.2.klib",
          "size": 714147,
          "sha512": "a752d28b20db1ce86d37338ff2ed77d1d86510e82e365ec86357e33226a3b14d2dd982326522a2d0351e65a3d071016c29e355492f2d6ece14b481a4e15c0257",
          "sha256": "e9ab282d281a719472031ff616cf53015e05f8e0bad315fb10c5b92f2bfa2a9b",
          "sha1": "727c2fe9f64c797c5eb976ccd19fa6bf6fe76218",
          "md5": "fee5583d2593839c354da9675c9e430f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.1.2.klib",
          "url": "toolkit-web-js-0.1.2.klib",
          "size": 714147,
          "sha512": "a752d28b20db1ce86d37338ff2ed77d1d86510e82e365ec86357e33226a3b14d2dd982326522a2d0351e65a3d071016c29e355492f2d6ece14b481a4e15c0257",
          "sha256": "e9ab282d281a719472031ff616cf53015e05f8e0bad315fb10c5b92f2bfa2a9b",
          "sha1": "727c2fe9f64c797c5eb976ccd19fa6bf6fe76218",
          "md5": "fee5583d2593839c354da9675c9e430f"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.1.2-sources.jar",
          "url": "toolkit-web-js-0.1.2-sources.jar",
          "size": 282050,
          "sha512": "fbb7e9f1517daa9224d428d809ec96ad307f8eb31a9338f1070bc000640b2a5bf32befb4f8f93a5b9bf969d1ce519d156d3253f0e0dcd1e90682c7bc99feff1d",
          "sha256": "b16d08790889305fde6b6630cc835a8aaf9dda8bb2cc5207fde6124b10a4c376",
          "sha1": "a1fb2b27fa8cf915699e8389aebf7084f576c1a9",
          "md5": "b38efbaae52b3a6844a3f2f6625e5de5"
        }
      ]
    }
  ]
}
