{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.0/toolkit-web-0.2.0.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.0.klib",
          "url": "toolkit-web-js-0.2.0.klib",
          "size": 630952,
          "sha512": "f1b9b57bd62c0c835bfb421c7e0f0957d3fe6abb18602bf2b2c31d129e882857cbc55d4c31fdf8f800cf09dc08fb09364e9cd1d25ee2febe2744efefd9ec10f6",
          "sha256": "577deb8c9a6e4dbeb9548a0ac1b1dc6019c39d731d3442e3e7690546ef87d6b6",
          "sha1": "b957e1d68de4abdc4d43f8fa6d650f8d55a475b6",
          "md5": "7e3f42372118740189ec6d6e38f1eb81"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.0.klib",
          "url": "toolkit-web-js-0.2.0.klib",
          "size": 630952,
          "sha512": "f1b9b57bd62c0c835bfb421c7e0f0957d3fe6abb18602bf2b2c31d129e882857cbc55d4c31fdf8f800cf09dc08fb09364e9cd1d25ee2febe2744efefd9ec10f6",
          "sha256": "577deb8c9a6e4dbeb9548a0ac1b1dc6019c39d731d3442e3e7690546ef87d6b6",
          "sha1": "b957e1d68de4abdc4d43f8fa6d650f8d55a475b6",
          "md5": "7e3f42372118740189ec6d6e38f1eb81"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.0-sources.jar",
          "url": "toolkit-web-js-0.2.0-sources.jar",
          "size": 257200,
          "sha512": "f6aa428fc6eae5870d2bf90b2c54592e1ede7ac0114e97dcc122c3f12ec940fba5adbc607a677ba8401daef4ef3a0db5757d4d7ec1d60755f3ebb3e1eb264ea4",
          "sha256": "510dfd6f8e683c96fc75c5dc76b285812c16a225c80fd0165843302d19d0487c",
          "sha1": "4d8614732a78f2370e337587e93fe0683742293e",
          "md5": "7b83558fad5758a2607e67824d273124"
        }
      ]
    }
  ]
}
