{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.12/toolkit-core-0.2.12.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.12.jar",
          "url": "toolkit-core-jvm-0.2.12.jar",
          "size": 77864,
          "sha512": "571d5a93a822a2575bfa5b82a2e278288f6593873ea5fed10e591fef3941c8674d6be5cde18fde15f4ad0657f940193455a0827c176c226e081ff68496664035",
          "sha256": "1e61df42f9dd49b63a46f3eb825b96bb738fe47f7a7b66134d0ac73ac2aef07c",
          "sha1": "c1a3c3e0bfbdbe70c66b0a3e8a08d83bbf2cf9e6",
          "md5": "d10387e4fd167d03eeadc4f8d89021d8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.12.jar",
          "url": "toolkit-core-jvm-0.2.12.jar",
          "size": 77864,
          "sha512": "571d5a93a822a2575bfa5b82a2e278288f6593873ea5fed10e591fef3941c8674d6be5cde18fde15f4ad0657f940193455a0827c176c226e081ff68496664035",
          "sha256": "1e61df42f9dd49b63a46f3eb825b96bb738fe47f7a7b66134d0ac73ac2aef07c",
          "sha1": "c1a3c3e0bfbdbe70c66b0a3e8a08d83bbf2cf9e6",
          "md5": "d10387e4fd167d03eeadc4f8d89021d8"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.12-sources.jar",
          "url": "toolkit-core-jvm-0.2.12-sources.jar",
          "size": 30623,
          "sha512": "5bbd8f0c95cc4b8a2b3cd50b34825b2164f5f2f7b7ce05b67d4a99cfca624538d8cd8ff9f779df4b529dbc5053aa20a9376ee8ae6db5189470ed192c0ba27b9e",
          "sha256": "4ba8e67f39ebe5fefe4534fab7ed6b0462b276f1bc44d4a8f4e831aedc4cebd4",
          "sha1": "26c09f0b3d090e2d0c8663a5f398c933f12c47dc",
          "md5": "70403f6326e7d998c64df00befc47d8f"
        }
      ]
    }
  ]
}
