{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-compose/0.1.2/toolkit-compose-0.1.2.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-compose",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-compose-jvm-0.1.2.jar",
          "url": "toolkit-compose-jvm-0.1.2.jar",
          "size": 4994,
          "sha512": "d01a040eb473831dd8ee322ebf24dcc994b81084c73db75b9265fd0bf0fdfe36873c0e1b590d67a86a30ceba66e7ad13098f4588f00a81606776782689ddf5f8",
          "sha256": "7dc450783b4711d1f25beb2fbe29c20629b333671ee7d3455273b5ca3c3f0fce",
          "sha1": "3a452d0b87043a349d9a1a2da7345a31d138caac",
          "md5": "8ae4e3967dd06abaeba46669b6418062"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-compose-jvm-0.1.2.jar",
          "url": "toolkit-compose-jvm-0.1.2.jar",
          "size": 4994,
          "sha512": "d01a040eb473831dd8ee322ebf24dcc994b81084c73db75b9265fd0bf0fdfe36873c0e1b590d67a86a30ceba66e7ad13098f4588f00a81606776782689ddf5f8",
          "sha256": "7dc450783b4711d1f25beb2fbe29c20629b333671ee7d3455273b5ca3c3f0fce",
          "sha1": "3a452d0b87043a349d9a1a2da7345a31d138caac",
          "md5": "8ae4e3967dd06abaeba46669b6418062"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-compose-jvm-0.1.2-sources.jar",
          "url": "toolkit-compose-jvm-0.1.2-sources.jar",
          "size": 2313,
          "sha512": "06e772c0d983c76d6de3e66032b99229a9b390d9382844dc452fdea0a89316a747071ebf8db61dce33405611c68585dff10b21ccd86da58ba0d2028ba290be89",
          "sha256": "e089282ea93552720c29ce6e82106afe38ad2d222db7a9489badbd3f27148025",
          "sha1": "da44815e59859b96e0a8c2e84239b33edff9637f",
          "md5": "64d1c8bde9c407fea3d9438ef71e4242"
        }
      ]
    }
  ]
}
