{
  "formatVersion": "1.1",
  "component": {
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-metadata-0.1.2.jar",
          "url": "toolkit-core-0.1.2.jar",
          "size": 14846,
          "sha512": "f21e041d957f06500b45ba2f05c1776edab6da52b015a55bbc6bd6cdccaf0b0345df3a161cb0f65b91ab51bd5b56e90e7305610e5422064ebcb8755694f46a18",
          "sha256": "08c7c1ebea17f5164c86ccb2c3546af8fe8cac15de402c8fc3d1d1eac32b1fa6",
          "sha1": "00633b0b98c253c22259de3cf37e4641d416549a",
          "md5": "deef1bc08ac69c33acff11ec230a6eef"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "toolkit-core-kotlin-0.1.2-sources.jar",
          "url": "toolkit-core-0.1.2-sources.jar",
          "size": 56147,
          "sha512": "1d0c38afdb8c994040cb68884e4686103e2fbcb860378f63ba907465df80d7bfceda2c0beb7d74edefa07b4a5055d010fc80f92e586d9f72a5c966c564a893ee",
          "sha256": "17c71597dad5f3ac723bb13ce7de2783b88b4625f1a5820ffa534a064a2606cb",
          "sha1": "c518ad71295c7ee773b9c3606c112bf77d6e6d28",
          "md5": "e25209611a9850f744164a2d1c260c5a"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toolkit-core-android/0.1.2/toolkit-core-android-0.1.2.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-android",
        "version": "0.1.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toolkit-core-android/0.1.2/toolkit-core-android-0.1.2.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-android",
        "version": "0.1.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toolkit-core-android/0.1.2/toolkit-core-android-0.1.2.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-android",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toolkit-core-iosarm64/0.1.2/toolkit-core-iosarm64-0.1.2.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-iosarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toolkit-core-iosarm64/0.1.2/toolkit-core-iosarm64-0.1.2.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-iosarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toolkit-core-iosarm64/0.1.2/toolkit-core-iosarm64-0.1.2.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-iosarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toolkit-core-iossimulatorarm64/0.1.2/toolkit-core-iossimulatorarm64-0.1.2.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-iossimulatorarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toolkit-core-iossimulatorarm64/0.1.2/toolkit-core-iossimulatorarm64-0.1.2.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-iossimulatorarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toolkit-core-iossimulatorarm64/0.1.2/toolkit-core-iossimulatorarm64-0.1.2.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-iossimulatorarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../toolkit-core-js/0.1.2/toolkit-core-js-0.1.2.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-js",
        "version": "0.1.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../toolkit-core-js/0.1.2/toolkit-core-js-0.1.2.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-js",
        "version": "0.1.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../toolkit-core-js/0.1.2/toolkit-core-js-0.1.2.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-js",
        "version": "0.1.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../toolkit-core-jvm/0.1.2/toolkit-core-jvm-0.1.2.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-jvm",
        "version": "0.1.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../toolkit-core-jvm/0.1.2/toolkit-core-jvm-0.1.2.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-jvm",
        "version": "0.1.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../toolkit-core-jvm/0.1.2/toolkit-core-jvm-0.1.2.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-jvm",
        "version": "0.1.2"
      }
    }
  ]
}
