{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.1.4/toolkit-store-0.1.4.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-jvm-0.1.4.jar",
          "url": "toolkit-store-jvm-0.1.4.jar",
          "size": 44565,
          "sha512": "72c5eb470819f246ec3c6abc419eb4821fd1dc6e8227ae7acaeb9e463f0647d337befdc6bdf92b0e359a715f0f29e4265b867712eed14a49bc202ecaabf89afa",
          "sha256": "cca693f78dcd82bc7d7f857a79fa050557358d35e304298091b54f54a479ec17",
          "sha1": "e3fb2b7924857c64baa81debd52ee3eafc67a375",
          "md5": "f524ccd522996991850ee0738503915b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-jvm-0.1.4.jar",
          "url": "toolkit-store-jvm-0.1.4.jar",
          "size": 44565,
          "sha512": "72c5eb470819f246ec3c6abc419eb4821fd1dc6e8227ae7acaeb9e463f0647d337befdc6bdf92b0e359a715f0f29e4265b867712eed14a49bc202ecaabf89afa",
          "sha256": "cca693f78dcd82bc7d7f857a79fa050557358d35e304298091b54f54a479ec17",
          "sha1": "e3fb2b7924857c64baa81debd52ee3eafc67a375",
          "md5": "f524ccd522996991850ee0738503915b"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-store-jvm-0.1.4-sources.jar",
          "url": "toolkit-store-jvm-0.1.4-sources.jar",
          "size": 18539,
          "sha512": "7c3f270b3e31a22e6dc4233d07ab3077b09bd95262da102e811f78ef1ba7f0fe2b7fc8b2ba66e2242a9ef6a9d9f7bc45c4fea1f813e441901b5d95142272acc0",
          "sha256": "c94d1fc34db0fef5df3c290719cc89c2db1586eeaecfddd032c9f5144042a52e",
          "sha1": "ba0714dddeffcc12e3e95bfe156597df530a84d3",
          "md5": "5bd3490d4f5de597d12c5b51dbad5a59"
        }
      ]
    }
  ]
}
