{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.1/toolkit-core-0.2.1.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iosArm64Main-0.2.1.klib",
          "url": "toolkit-core-iosarm64-0.2.1.klib",
          "size": 108308,
          "sha512": "54f7748b3e56975bcfd1932c7e1d3f90c17dd2899db690cd2aada1161cba3bf951eab4a2d891b73a635e77e98b594b38f14e87700d51cf89d2f72ac88d34c4cf",
          "sha256": "0b962f0d84f126b0b7276833a43d5d180163a90d39c8dee77a257a8b5ed53c7b",
          "sha1": "395f6140fa5c7a1244230dc7da17db34f6dd470d",
          "md5": "d42e08f29dff310faec1e4d484461db4"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-core-iosarm64-0.2.1-sources.jar",
          "url": "toolkit-core-iosarm64-0.2.1-sources.jar",
          "size": 30354,
          "sha512": "e0ac19659bc0ce0fdbee13ef1ca1a760cd564e543681d7dc61eac1d4c4df4b87d00add402f5ff12e7766b1ed40eababd9090d985593f10b5b6921d49268ed251",
          "sha256": "925b11edd673510395469156bd0548e6c0f4234237727d4d48935e758c6ce73c",
          "sha1": "1c10482b7c393cbf36af436629229429346b06ea",
          "md5": "5025f4d132c82eee54ee752e9c367378"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iosarm64-0.2.1-metadata.jar",
          "url": "toolkit-core-iosarm64-0.2.1-metadata.jar",
          "size": 261,
          "sha512": "e3c6420c98b97e7ed60736403943aa0b612d1a9f2a183fdd941f205791e52b969b679de57e759f9aef245b2c71f52ab1a3f9f6eacbba0d1f09b24c934cc96264",
          "sha256": "7dfaa378fe70d46ca4654e044ad1aaf64b345bd0782e748f779b230adae3b918",
          "sha1": "c36cf693a13b9aed21c29953b503e8b978cc907c",
          "md5": "557dd3a29d5ecbe2ee7d4c1fda2469fc"
        }
      ]
    }
  ]
}
