{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.12/toolkit-core-0.2.12.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iosArm64Main-0.2.12.klib",
          "url": "toolkit-core-iosarm64-0.2.12.klib",
          "size": 108741,
          "sha512": "83649f1fea9edc2e624b9af605f856332c7613897e2f45bcd2296710608f65f615898dd9ae8c7d0a01e2be35daaa891d44820a548872cc0c0a17d45eff5341c9",
          "sha256": "0845fad6f5347721ba814554688575497206df3401436960df897a961f2dea4d",
          "sha1": "5e76107908c18288881598c37221c5c47d032d78",
          "md5": "58845c17aba4f78d8567adca694ac503"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-core-iosarm64-0.2.12-sources.jar",
          "url": "toolkit-core-iosarm64-0.2.12-sources.jar",
          "size": 30623,
          "sha512": "5bbd8f0c95cc4b8a2b3cd50b34825b2164f5f2f7b7ce05b67d4a99cfca624538d8cd8ff9f779df4b529dbc5053aa20a9376ee8ae6db5189470ed192c0ba27b9e",
          "sha256": "4ba8e67f39ebe5fefe4534fab7ed6b0462b276f1bc44d4a8f4e831aedc4cebd4",
          "sha1": "26c09f0b3d090e2d0c8663a5f398c933f12c47dc",
          "md5": "70403f6326e7d998c64df00befc47d8f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iosarm64-0.2.12-metadata.jar",
          "url": "toolkit-core-iosarm64-0.2.12-metadata.jar",
          "size": 261,
          "sha512": "15325aec34834c5ecdf49b4598e4140f748e8a13db75676aa182cd6651ff29ee26c892af63559aebf222a69ff4489014a414446ca94aad9d043c08f87d5d3f78",
          "sha256": "c288ccd6ea942aa1727ee4d70389a5f3291181760afe574d99df0a0bcab0e29c",
          "sha1": "cccb3da2e1dd45154611fdb703cacf7ed4731779",
          "md5": "dff3c8d297c09f385aadc0375d157a27"
        }
      ]
    }
  ]
}
