{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.1.1/toolkit-core-0.1.1.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-js-0.1.1.klib",
          "url": "toolkit-core-js-0.1.1.klib",
          "size": 168611,
          "sha512": "23a84ca9f654e58b280ed5a44a85ca2a67e18a921683146d4e80a148c02390e85262c0021b865c4aae51863231ed96925784624225b240905f2806e99c4d6bc5",
          "sha256": "d83e19eaeb80793bdfdba031f9031e060f9e117ac685414f60ecddeb7d6851bb",
          "sha1": "e88556905a5c40034021e6875d51679d9c4ac9a6",
          "md5": "4e5e7db006dd805f801e5145834e5ef9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-js-0.1.1.klib",
          "url": "toolkit-core-js-0.1.1.klib",
          "size": 168611,
          "sha512": "23a84ca9f654e58b280ed5a44a85ca2a67e18a921683146d4e80a148c02390e85262c0021b865c4aae51863231ed96925784624225b240905f2806e99c4d6bc5",
          "sha256": "d83e19eaeb80793bdfdba031f9031e060f9e117ac685414f60ecddeb7d6851bb",
          "sha1": "e88556905a5c40034021e6875d51679d9c4ac9a6",
          "md5": "4e5e7db006dd805f801e5145834e5ef9"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-core-js-0.1.1-sources.jar",
          "url": "toolkit-core-js-0.1.1-sources.jar",
          "size": 56147,
          "sha512": "1d0c38afdb8c994040cb68884e4686103e2fbcb860378f63ba907465df80d7bfceda2c0beb7d74edefa07b4a5055d010fc80f92e586d9f72a5c966c564a893ee",
          "sha256": "17c71597dad5f3ac723bb13ce7de2783b88b4625f1a5820ffa534a064a2606cb",
          "sha1": "c518ad71295c7ee773b9c3606c112bf77d6e6d28",
          "md5": "e25209611a9850f744164a2d1c260c5a"
        }
      ]
    }
  ]
}
